---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 上午 05:14
---

---@class Mth
local m = {}
Mth = m

---@param number number
---@return number
function m.sin(number) end

---@param number number
---@return number
function m.cos(number) end

---@param number number
---@return number
function m.sqrt(number) end

---@param a number
---@param b number
---@param t number
---@return number
function m.lerp(a, b, t) end
--[[
---@param number number
---@return number
function Mth.floor(number) end

---@param number number
---@return number
function Mth.lfloor(number) end

---@param number number
---@return number
function Mth.abs(number) end

---@param number number
---@return number
function Mth.ceil(number) end

---@param number number
---@param max number
---@param min number
---@return number
function Mth.clamp(number, max, min) end

---@param number number
---@param number2 number
---@return boolean
function Mth.equal(number,number2) end
]]