---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/1/18 上午 04:26
---

---@class core.Vec3
---@field x number
---@field y number
---@field z number
local Vec3 = {}

---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:vectorTo(vec3) end

---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:normalize(vec3) end

---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:dot(vec3) end

---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:cross(vec3) end

---@overload fun(x:number,y:number,z:number)
---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:subtract(vec3) end

---@overload fun(x:number,y:number,z:number)
---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:add(vec3) end

---@param vec3 core.Vec3
---@return number
function Vec3:distanceTo(vec3) end

---@overload fun(x:number,y:number,z:number)
---@param vec3 core.Vec3
---@return number
function Vec3:distanceToSqr(vec3) end

---@param number number
---@return core.Vec3
function Vec3:scale(number) end

---@return core.Vec3
function Vec3:reverse() end

---@overload fun(x:number,y:number,z:number)
---@param vec3 core.Vec3
---@return core.Vec3
function Vec3:multiply(vec3) end

---@param vec3 core.Vec3
---@return boolean
function Vec3:equals(vec3) end

---@param number number
---@return core.Vec3
function Vec3:xRot(number) end

---@param number number
---@return core.Vec3
function Vec3:yRot(number) end

---@param number number
---@return core.Vec3
function Vec3:zRot(number) end

---@param vec2 core.Vec2
---@return core.Vec3
function Vec3:directionFromRotation(vec2) end

---@return number
function Vec3:x() end

---@return number
function Vec3:y() end

---@return number
function Vec3:z() end