---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/27 下午 08:26
---

---@type Class|THObject
THObjectBase = core.defineClass("THObject_Base")
local o = THObjectBase
o.thobject_type = "THObject_Base"

function o:onInit(vec3)
    self:initPosition(vec3)
end

function o:onAddTasks()
end

function o:onTick()
end

function o:onHit()
end

function o:onDead()
end

function o:onRemove()
end