---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/20 下午 07:05
---

---@class AutoSaveData
local AutoSaveData = {}

---@param key string
function AutoSaveData:register(key) end

---@param key string
function AutoSaveData:unregister(key) end