---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/31 13:23
---

---@class THBullet:THObject
local bullet = {}

---@param style string
function bullet:setStyle(style) end

---@param colorIndex number
function bullet:setBulletColorByIndex(colorIndex) end

---@param r number
---@param g number
---@param b number
---@param a number
function bullet:setBulletColor(r,g,b,a) end

---@return string
function bullet:getStyle() end

---@return table
function bullet:getBulletColor() end

THBullet = bullet