---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/27 下午 09:07
---

---@class abstractVec3
---@field x number
---@field y number
---@field z number
local abstractVec3 = {}