---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/16 上午 12:31
---


---@type Class|THObjectContainer
local yukari_spellcrad_1 = core.defineClass("yukari_spellcard_1")
function yukari_spellcrad_1:onInit()
    self:setSpellCardName("Border Sign \"Boundary of Truth and Falsehood\"")
    self:setLifetime(300)
end

function yukari_spellcrad_1:onTick()
    local timer = self:getTimer()

    ---@param _pos util.Vec3
    ---@param _angle util.Vec3
    local bbb = function(_pos,_angle)
        local bullet2 = self:createTHBullet(nil, {i}, _pos,"arrow_big",3)
        bullet2:setPosition(_pos:add(_angle:scale(math.min(timer/120,1)^0.4*1.6)))
        bullet2:setVelocity(_angle:scale(0.2),true)
        bullet2:setAccelerationFromDirection(0.02,_angle)
        bullet2:setLifetime(120)
        bullet2:setBlend("add")
    end

    if timer < 300 then
        local pos = self:getPosition()
        local rotation = util.vec3.new(0.0,0.0,1.0)
        local way = 6
        local rotate = util.vec2.new(
                Mth.DEG_TO_RAD*(math.pow(timer*0.1,2)+360/way),
                -Mth.DEG_TO_RAD*(math.pow(timer*0.08,2)+360/way))

        local angle = rotation:xRot(Mth.DEG_TO_RAD*90):xRot(rotate.x):yRot(rotate.y)
        bbb(pos,angle)

        local way2 = 4
        for i=1,(way2-1) do
            local angle2 = rotation:xRot(Mth.DEG_TO_RAD*90-Mth.DEG_TO_RAD*(180/way2)*i):yRot(Mth.DEG_TO_RAD*(180/way)*i)
            for j=0,(way) do
                local angle3 = angle2:yRot(-Mth.DEG_TO_RAD*(360/way)*j):normalize():xRot(rotate.x):yRot(rotate.y)
                bbb(pos,angle3)
            end
        end
        local angle3 = rotation:xRot(Mth.DEG_TO_RAD*90-Mth.DEG_TO_RAD*180):xRot(rotate.x):yRot(rotate.y)
        bbb(pos,angle3)
    end
end