---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/17 上午 01:29
---

bullet_styles = {
    arrow_big = "arrow_big",
    arrow_mid = "arrow_mid",
    arrow_small = "arrow_small",
    gun_bullet = "gun_bullet",
    butterfly = "butterfly",
    square = "square",
    ball_small = "ball_small",
    ball_mid = "ball_mid",
    ball_mid_c = "ball_mid_c",
    ball_big = "ball_big",
    ball_huge = "ball_huge",
    ball_light = "ball_light",
    star_small = "star_small",
    star_big = "star_big",
    grain_a = "grain_a",
    grain_b = "grain_b",
    grain_c = "grain_c",
    kite = "kite",
    knife = "knife",
    knife_b = "knife_b",
    water_drop = "water_drop",
    mildew = "mildew",
    ellipse = "ellipse",
    heart = "heart",
    money = "money",
    music = "music",
    silence = "silence",
    water_drop_dark = "water_drop_dark",
    ball_huge_dark = "ball_huge_dark",
    ball_light_dark = "ball_light_dark",
}