---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/20 上午 12:30
---

---@class TaskManager
local TaskManager = {}

---@param name string
---@param lifetime number
---@param runnable fun(target:any,timer:number)
function TaskManager:registerTask(name, lifetime, runnable) end

---@param name string
function TaskManager:startTask(name) end

---@param name string
function TaskManager:removeTask(name) end

function TaskManager:clearTasks() end