---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/20 上午 12:30
---

---@class TaskManager
local TaskManager = {}

---@param task_name string
---@param task_life number
---@param task_runnable fun(target:any,timer:number)
function TaskManager:registerTask(task_name, task_life, task_runnable) end

---@param task_name string
function TaskManager:startTask(task_name) end

---@param task_name string
function TaskManager:removeTask(task_name) end

function TaskManager:clearTasks() end