---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/19 下午 08:45
---

core.doFile("lib/thobject/thobject_container_base.lua")
core.doFile("lib/thobject/thobject_base.lua")