---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/1/18 上午 04:26
---

---@class Vec3
local Vec3 = {
    x,
    y,
    z
}

---@param vec3 Vec3
---@return Vec3
function Vec3:vectorTo(vec3)
end

---@param vec3 Vec3
---@return Vec3
function Vec3:normalize(vec3)
end

---@param vec3 Vec3
---@return Vec3
function Vec3:dot(vec3)
end