---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/4 14:05
---

---@class Class
---@field className string
---@field super Class
local class = {}

class.type = "class"

---@return boolean
function class:isInstanceof(class2) end