---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/24 下午 05:06
---

local map = {}

function map.new()
    local m = {}
    setmetatable(m, {__index = map})
    return
end

function map:put(key, value)
    self[key] = value
end

function map:get(key)
    return self[key]
end

function map:remove(key)
    self[key] = nil
end

function map:clear()
    for k, v in pairs(self) do
        self[k] = nil
    end
end

function map:size()
    return #self
end

function map:containsKey(key)
    return self[key] ~= nil
end

function map:containsValue(value)
    for k, v in pairs(self) do
        if v == value then
            return true
        end
    end
    return false
end

---@param func fun(key, value)
function map:forEach(func)
    for k, v in pairs(self) do
        func(k, v)
    end
end