---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/12/5 上午 12:06
---

local function clone(table)
    local newTable = {}
    for key,value in ipairs(table) do
        local metatable = getmetatable(table)
        setmetatable(newTable,metatable)
        if table(value) == 'table' then
            newTable[key] = clone(value)
        else
            newTable[key] = value
        end
    end
    return newTable
end

table.clone = clone
