---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/12/5 上午 12:06
---

local function clone(table)
    local newTable = {}
    for key,value in ipairs(table) do
        newTable[key] = value
    end
    return newTable
end

table.clone = clone
