---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/9 23:35
---

---@class Task
local task = {}

---@param taskName string
---@param runnable function
function task.create(taskName, runnable)
    local task = {}
    task.coroutine = coroutine.create(runnable)

end

---@param time number
function task.wait(time)
    time = time or 1
    time = max(1, int(time))
    for i = 1, time do
        coroutine.yield()
    end
end
