---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/9 23:35
---

---@class Task
---@field progress number
---@field co thread
---@field runnable fun(target:table)
task = {}

---@param target table
---@param runnable fun(target:table)
---@return Task
function task.new(runnable)
    ---@type Task
    local t = {}
    t.progress = 0
    t.runnable = runnable
    t.co = coroutine.create(t.runnable)
    return t
end

---@param time number
function task.wait(time)
    for i = 0, (time or 1) do
        coroutine.yield()
    end
end