---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/19 下午 08:42
---
core.doFile("lib/lib.lua")
core.doFile("spellcard/spellcard.lua")
core.doFile("testcontainer.lua")