---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/3/12 上午 02:42
---

---@type Class|THBullet
THBulletBase = core.defineClass("THBullet_Base",THObjectBase)
local bullet = THBulletBase
bullet.thobject_type = core.thobject_types.bullet

---@param position util.Vec3
---@param style string
---@param colorIndex number
function bullet:onInit(position,style,colorIndex)
    THObjectBase.onInit(self,position)
    self:setStyle(style)
    self:setBulletColorByIndex(colorIndex)
end

---@param className string
---@return Class|THObject
util.defineTHBullet = function(className)
    return core.defineClass(className,THBulletBase)
end