---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/19 下午 08:04
---

---@type Class|THObjectContainer
THObjectContainerBase = core.defineClass("THObjectContainer_Base")
local container = THObjectContainerBase
---此函數會在THObjectContainer創建時調用
function container:onConstruct()
end

----此函數會在註冊Tasks時被調用
---@param taskManager TaskManager
function container:onRegisterTasks(taskManager)

end

---此函數會在THObjectContainer第一次添加到world時調用
function container:onInit()
end

---此函數會在THObjectContainer每次tick時調用
function container:onTick()
end