---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 下午 10:27
---

---@class core
---@field super Class
local core = {}

---@param path string
function core.doFile(path) end

---@param object userdata
---@return boolean
function core.isValid(object) end

---@param msg string
function core.info(msg) end

---@param msg string
function core.warn(msg) end

---@param x number
---@param y number
---@return Vec2
function core.newVec2(x,y) end

---@param x number
---@param y number
---@param z number
---@return Vec3
function core.newVec3(x,y,z) end

---@param className string
---@param parentClass Class
---@return Class
---@overload fun(className:string, parentClass:Class)
---@overload fun(className:string, parentClassName:string)
function core.registerClass(className, parentClass) end

---@param className self
---@return Class
function core.getClass(className) end