---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/2 16:45
---

---@class Entity
local entity = {}

---@return util.Vec3
function entity:getPosition() end

---@return core.Vec2
function entity:getRotation() end