---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/31 13:35
---

---@class THCurvedLaser:THObject
local laser = {}

---@class LaserNode
local node = {}

---@return number
function laser:getNodeMount() end

---@return LaserNode
function laser:getNode(index) end

---@return table|LaserNode
function laser:getAllNodes() end

---@param index number
---@param pos Vec3
function laser:setNode(index, pos) end

---@param pos Vec3
function node:updateNode(pos) end

---@param pos Vec3
function node:setPosition(pos) end

---@return Vec3
function node:getPosition() end