---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/16 上午 02:55
---


local m = math

---@param t number
---@param a number
---@param b number
---@return number
function m.lerp(a, b, t)
    return a + t * (b - a);
end

---@param number number
---@param min number
---@param max number
---@return number
function m.clamp(number, min, max)
    return math.max(math.min(number, max), min);
end

