---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/16 上午 02:55
---


local m = math

---@param a number
---@param b number
---@param t number
---@return number
function m.lerp(a, b, t)
    return b + a * (t - b);
end

---@param number number
---@param min number
---@param max number
---@return number
function m.clamp(number, min, max)
    return math.max(math.min(number, max), min);
end

