---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 下午 10:27
---

---@class core
local core = {}

---@param path string
function core:doFile(path) end

---@param object userdata
function core:isValid(object) end

---@param msg string
---@see
function core:info(msg) end

---@param msg string
function core:warn(msg) end
