---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/31 13:23
---

---@class THBullet:THObject
local bullet = {}

---@param style string
function bullet:setStyle(style) end

---@param colorIndex number
function bullet:setBulletColor(colorIndex) end

---@return string
function bullet:getStyleName() end

---@return number
function bullet:getBulletColorIndex() end

THBulletClass = bullet