---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/31 01:08
---

---@class THObjectContainer
---@field onInit fun(self)
---@field onTick fun(self)
local container = {
}

---@return number
function container:getMaxObjectAmount() end

---@return Vec3
function container:getPosition() end

---@param time number
function container:setTimer(time) end

---@return number
function container:getTimer() end

function container:clearObjects() end

---@param position Vec3
---@return THObject
function container:createTHObject(position) end

---@param position Vec3
---@param style string
---@param colorIndex number
---@return THBullet
function container:createTHBullet(position,style,colorIndex) end

container:createTHBullet()

---@param position Vec3
---@param colorIndex number
---@param length number
---@param width number
---@return THCurvedLaser
function container:createTHCurvedLaser(position,colorIndex,length,width) end
