---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/12/4 上午 02:15
---

---@class THObject
local THObject = {
    ---@param self THObject
    onInit  = function(self) end,

    ---@param self THObject
    onTick  = function(self) end,

    ---@param self THObject
    onHit   = function(self) end,

    ---@param self THObject
    onDeath = function(self) end,

    ---@type number
    x = 0.0,
    ---@type number
    y = 0.0,
    ---@type number
    z = 0.0,


}