---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 下午 10:29
---

--[[
minecraft = {}

minecraft.Mth             = luajava.bindClass('net.minecraft.util.Mth')
minecraft.Vec2            = luajava.bindClass('net.minecraft.world.phys.Vec2')
minecraft.Vec3            = luajava.bindClass('net.minecraft.world.phys.Vec3')
minecraft.THObject        = luajava.bindClass('com.adrian.thDanmakuCraft.world.entity.danmaku.THObject')
minecraft.THBullet        = luajava.bindClass('com.adrian.thDanmakuCraft.world.entity.danmaku.THBullet')
minecraft.THCurvedLaser   = luajava.bindClass('com.adrian.thDanmakuCraft.world.entity.danmaku.laser.THCurvedLaser')

Mth = minecraft.Mth
]]

---@class Vec3
vec3 = luajava.new(Vec3,1.0,2.0,1.0)

local num = Mth:abs(-10.0)

print(core)
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
core.info("sadsadsadsadsadsadasasdasdadassadsadsadsadadasd")
--core:doFile("test.lua")
--core:doFile("test.lua")
print(vec3:xRot(10.0).y .."aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffff")
--core:info("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")

local co1 = coroutine.create(function()
    print("1aaaaaaaaa")
    coroutine.yield()
    print("2aaaaaaaaaaaaa")
    coroutine.yield()
    print("3aaaaaaaaaaaaaaaaaaaaaaa")
end)

coroutine.resume(co1)
print("asffasdasd")
coroutine.resume(co1)
print("asffasdasd")
coroutine.resume(co1)