---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 下午 10:29
---
New = luajava.new

core.doFile("lib.lua")
--core.doFile("core/doc/vec3.lua")
--core.doFile("core/doc/vec2.lua")
--[[
core.doFile("doc/vec3.lua")
core.doFile("doc/vec2.lua")
]]
