---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/17 02:53
---

---@type THObjectContainer
local container = core.registerClass("testContainer4")

function container:onInit()
end

function container:onTick()
    local timer = self:getTimer()
    local pos = self:getPosition()
end