---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 上午 05:14
---

---@class Mth
Mth = {}

---@param number number
---@return number
function Mth.sin(number) end

---@param number number
---@return number
function Mth.cos(number) end

---@param number number
---@return number
function Mth.sqrt(number) end

---@param a number
---@param b number
---@param t number
---@return number
function Mth.lerp(a, b, t) end
--[[
---@param number number
---@return number
function Mth.floor(number) end

---@param number number
---@return number
function Mth.lfloor(number) end

---@param number number
---@return number
function Mth.abs(number) end

---@param number number
---@return number
function Mth.ceil(number) end

---@param number number
---@param max number
---@param min number
---@return number
function Mth.clamp(number, max, min) end

---@param number number
---@param number2 number
---@return boolean
function Mth.equal(number,number2) end
]]