---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/31 01:59
---

---@class Vector3f
---@field x number
---@field y number
---@field z number
local Vector3f = {}

---@return number
function Vector3f:x() end

---@return number
function Vector3f:y() end

---@return number
function Vector3f:z() end