---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/7 下午 10:27
---

---@class core
core = {}

---@param filePath string
function core.doFile(filePath) end

---@param object any
---@return boolean
function core.isValid(object) end

---@param msg string
function core.info(msg) end

---@param msg string
function core.warn(msg) end

---@param x number
---@param y number
---@return Vec2
function core.vec2(x, y) end

---@param x number
---@param y number
---@param z number
---@return Vec3
function core.vec3(x, y, z) end

---@param className string
---@param parentClass Class
---@return Class
---@overload fun(className:string, superClass:Class)
---@overload fun(className:string, superClass:string)
---@overload fun()
---@overload fun(superClass:Class)
function core.registerClass(className, superClass) end

---@param className self
---@return Class
function core.getClass(className) end